In [1]:
print("hello world")

hello world


In [2]:
import numpy as np

In [9]:

numbers = np.array([10, 20, 30, 40])
print(numbers)  
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [10]:
prices = np.array([100, 250, 500])
discounted_prices = prices * 0.90
print(discounted_prices)
bonus = np.array([5, 10, 15])
final_prices = discounted_prices + bonus
print(final_prices)

[ 90. 225. 450.]
[ 95. 235. 465.]


In [24]:
scores = np.array([85, 92, 78, 99, 88])
print(np.mean(scores))  
print(np.max(scores))       
print(np.min(scores))       

88.4
99
78


In [12]:
ages = np.array([14, 22, 17, 35, 41, 12, 19])
is_adult = ages >= 18
adult_ages = ages[is_adult]
print(adult_ages)

[22 35 41 19]


In [13]:
flat_data = np.array([1, 2, 3, 4, 5, 6])
matrix = flat_data.reshape(2, 3)
print(matrix)

[[1 2 3]
 [4 5 6]]


In [14]:
numbers = np.array([15, 3, 99, 42, 1])
sorted_numbers = np.sort(numbers)
print(sorted_numbers)

[ 1  3 15 42 99]


In [16]:
salaries = np.array([2500, 3100, np.nan, 4000])
clean_average = np.nanmean(salaries)
print(clean_average)

3200.0


In [17]:
data = np.array([10, np.nan, 30, np.nan, 50])
clean_data = data[~np.isnan(data)]
print(clean_data)  
data[np.isnan(data)] = 0
print(data)        

[10. 30. 50.]
[10.  0. 30.  0. 50.]


In [19]:
box = np.array([[1, 2, 3], [4, 5, 6]])
print(box.size)  
print(box.shape) 

6
(2, 3)


In [23]:
fruits = np.array(["Apple", "Banana", "Cherry"])

print(fruits[::-1])

['Cherry' 'Banana' 'Apple']
